version: '3'

networks:
  my-network:
    driver: bridge

services:
  main-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - my-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
#      KAFKA_BROKER_URL: "kafka-service:9092"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - order_db
#      - kafka-service
    networks:
      - my-network

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - payment_db
    networks:
      - my-network

  saga-service:
    build:
      context: .
      dockerfile: saga-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - my-network

#  kafka-service:
#    image: confluentinc/cp-kafka:latest
#    ports:
#      - "9092:9092"
#    networks:
#      - my-network
#    environment:
#      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093"
#      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka-service:9092,OUTSIDE://kafka-service:9093"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
#      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
#
#  zookeeper-service:
#    image: wurstmeister/zookeeper:latest
#    ports:
#      - "2181:2181"
#    networks:
#      - my-network
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536

  order_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: aleksa
      POSTGRES_PASSWORD: aleksa
    ports:
      - "5432:5432"
    networks:
      - my-network

  payment_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: aleksa
      POSTGRES_PASSWORD: aleksa
    ports:
      - "5433:5432"
    networks:
      - my-network


