logging:
  level:
    root: INFO
spring:
  application:
    name: "Food Service"
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/food_db"
    username: "aleksa"
    password: "aleksa"
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
  servlet:
    context-path: "/api"

